package Entities;

import java.util.Date;

/**
 * Employees generated by hbm2java
 */
public class Employees {


    private Integer id;
    private String username;
    private String password;
    private String firstName;
    private String lastName;
    private String position;
    private Integer salary;

    public Employees() {
    }

    public Employees(String username, String password) {
        this.username = username;
        this.password = password;
    }

    public Employees(String username, String password, String firstName, String lastName, String position,
                     Integer salary) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.position = position;
        this.salary = salary;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPosition() {
        return this.position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public Integer getSalary() {
        return this.salary;
    }

    public void setSalary(Integer salary) {
        this.salary = salary;
    }

}



