CREATE TABLE [Books] (
[BookID] INTEGER  PRIMARY KEY NOT NULL,
[Name] VARCHAR(60)  NULL,
[Author] VARCHAR(30)  NULL,
[Category] VARCHAR(20)  NULL,
[Cover] VARCHAR(60)  NULL,
[Review] TEXT  NULL,
[Price] INTEGER DEFAULT '0' NULL,
[UnitsInStock] INTEGER DEFAULT '0' NULL,
[UnitsOnOrder] INTEGER DEFAULT '0' NULL,
[Virtual] BOOLEAN  NULL,
[Owner] VARCHAR(30)  NULL
);

CREATE TABLE [Customers] (
[CustomerID] INTEGER  PRIMARY KEY NOT NULL,
[FirstName] VARCHAR(30)  NULL,
[LastName] VARCHAR(20)  NULL,
[Email] VARCHAR(30)  NULL,
[Phone] VARCHAR(15)  NULL,
[Sex] VARCHAR(5)  NULL,
[Address] VARCHAR(100)  NULL
);

CREATE TABLE [OrderDetail] (
[OrderID] INTEGER  NOT NULL,
[BookID] INTEGER  NULL,
[Quantity] INTEGER DEFAULT '0' NULL
);

CREATE TABLE [Orders] (
[OrderID] INTEGER  PRIMARY KEY NOT NULL,
[CustomerID] INTEGER  NOT NULL,
[OrderDate] DATE  NULL
);

CREATE TABLE [Owner] (
[OwnerID] INTEGER  NOT NULL PRIMARY KEY,
[Name] VARCHAR(60)  NULL,
[Email] VARCHAR(60)  NULL,
[Phone] VARCHAR(20)  NULL,
[Address] VARCHAR(100)  NULL,
[University] VARCHAR(10) DEFAULT 'UIT' NULL
);
