package com.app.bookstoreapp.entity;
// Generated Nov 8, 2018 10:55:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Authors generated by hbm2java
 */
public class Authors  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private Set bookses = new HashSet(0);

    public Authors() {
    }

    public Authors(String firstName, String lastName, Set bookses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.bookses = bookses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Set getBookses() {
        return this.bookses;
    }
    
    public void setBookses(Set bookses) {
        this.bookses = bookses;
    }




}


