package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Baocaocongno generated by hbm2java
 */
public class Baocaocongno  implements java.io.Serializable {


     private int mano;
     private Date thangno;
     private Set ctCongnos = new HashSet(0);

    public Baocaocongno() {
    }

	
    public Baocaocongno(int mano) {
        this.mano = mano;
    }
    public Baocaocongno(int mano, Date thangno, Set ctCongnos) {
       this.mano = mano;
       this.thangno = thangno;
       this.ctCongnos = ctCongnos;
    }
   
    public int getMano() {
        return this.mano;
    }
    
    public void setMano(int mano) {
        this.mano = mano;
    }
    public Date getThangno() {
        return this.thangno;
    }
    
    public void setThangno(Date thangno) {
        this.thangno = thangno;
    }
    public Set getCtCongnos() {
        return this.ctCongnos;
    }
    
    public void setCtCongnos(Set ctCongnos) {
        this.ctCongnos = ctCongnos;
    }




}


