package com.app.bookstoreapp.entity;
// Generated Nov 8, 2018 10:55:04 AM by Hibernate Tools 4.3.1



/**
 * BooksDiscounts generated by hbm2java
 */
public class BooksDiscounts  implements java.io.Serializable {


     private BooksDiscountsId id;
     private Books books;
     private Discounts discounts;

    public BooksDiscounts() {
    }

	
    public BooksDiscounts(BooksDiscountsId id) {
        this.id = id;
    }
    public BooksDiscounts(BooksDiscountsId id, Books books, Discounts discounts) {
       this.id = id;
       this.books = books;
       this.discounts = discounts;
    }
   
    public BooksDiscountsId getId() {
        return this.id;
    }
    
    public void setId(BooksDiscountsId id) {
        this.id = id;
    }
    public Books getBooks() {
        return this.books;
    }
    
    public void setBooks(Books books) {
        this.books = books;
    }
    public Discounts getDiscounts() {
        return this.discounts;
    }
    
    public void setDiscounts(Discounts discounts) {
        this.discounts = discounts;
    }




}


