package com.app.bookstoreapp.entity;
// Generated Nov 8, 2018 10:55:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Books generated by hbm2java
 */
public class Books  implements java.io.Serializable {


     private Integer id;
     private Authors authors;
     private Genres genres;
     private Publishers publishers;
     private String isbn;
     private String title;
     private Integer publicationYear;
     private Integer price;
     private Integer availableQuantity;
     private Set booksDiscountses = new HashSet(0);

    public Books() {
    }

	
    public Books(Authors authors) {
        this.authors = authors;
    }
    public Books(Authors authors, Genres genres, Publishers publishers, String isbn, String title, Integer publicationYear, Integer price, Integer availableQuantity, Set booksDiscountses) {
       this.authors = authors;
       this.genres = genres;
       this.publishers = publishers;
       this.isbn = isbn;
       this.title = title;
       this.publicationYear = publicationYear;
       this.price = price;
       this.availableQuantity = availableQuantity;
       this.booksDiscountses = booksDiscountses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Authors getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Authors authors) {
        this.authors = authors;
    }
    public Genres getGenres() {
        return this.genres;
    }
    
    public void setGenres(Genres genres) {
        this.genres = genres;
    }
    public Publishers getPublishers() {
        return this.publishers;
    }
    
    public void setPublishers(Publishers publishers) {
        this.publishers = publishers;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Integer getPublicationYear() {
        return this.publicationYear;
    }
    
    public void setPublicationYear(Integer publicationYear) {
        this.publicationYear = publicationYear;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getAvailableQuantity() {
        return this.availableQuantity;
    }
    
    public void setAvailableQuantity(Integer availableQuantity) {
        this.availableQuantity = availableQuantity;
    }
    public Set getBooksDiscountses() {
        return this.booksDiscountses;
    }
    
    public void setBooksDiscountses(Set booksDiscountses) {
        this.booksDiscountses = booksDiscountses;
    }




}


