package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1



/**
 * CtCongnoId generated by hbm2java
 */
public class CtCongnoId  implements java.io.Serializable {


     private int mano;
     private int makh;

    public CtCongnoId() {
    }

    public CtCongnoId(int mano, int makh) {
       this.mano = mano;
       this.makh = makh;
    }
   
    public int getMano() {
        return this.mano;
    }
    
    public void setMano(int mano) {
        this.mano = mano;
    }
    public int getMakh() {
        return this.makh;
    }
    
    public void setMakh(int makh) {
        this.makh = makh;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CtCongnoId) ) return false;
		 CtCongnoId castOther = ( CtCongnoId ) other; 
         
		 return (this.getMano()==castOther.getMano())
 && (this.getMakh()==castOther.getMakh());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMano();
         result = 37 * result + this.getMakh();
         return result;
   }   


}


