package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1



/**
 * CtCongno generated by hbm2java
 */
public class CtCongno  implements java.io.Serializable {


     private CtCongnoId id;
     private Baocaocongno baocaocongno;
     private Khachhang khachhang;
     private Integer nodau;
     private Integer phatsinh;
     private Integer nocuoi;

    public CtCongno() {
    }

	
    public CtCongno(CtCongnoId id, Baocaocongno baocaocongno, Khachhang khachhang) {
        this.id = id;
        this.baocaocongno = baocaocongno;
        this.khachhang = khachhang;
    }
    public CtCongno(CtCongnoId id, Baocaocongno baocaocongno, Khachhang khachhang, Integer nodau, Integer phatsinh, Integer nocuoi) {
       this.id = id;
       this.baocaocongno = baocaocongno;
       this.khachhang = khachhang;
       this.nodau = nodau;
       this.phatsinh = phatsinh;
       this.nocuoi = nocuoi;
    }
   
    public CtCongnoId getId() {
        return this.id;
    }
    
    public void setId(CtCongnoId id) {
        this.id = id;
    }
    public Baocaocongno getBaocaocongno() {
        return this.baocaocongno;
    }
    
    public void setBaocaocongno(Baocaocongno baocaocongno) {
        this.baocaocongno = baocaocongno;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Integer getNodau() {
        return this.nodau;
    }
    
    public void setNodau(Integer nodau) {
        this.nodau = nodau;
    }
    public Integer getPhatsinh() {
        return this.phatsinh;
    }
    
    public void setPhatsinh(Integer phatsinh) {
        this.phatsinh = phatsinh;
    }
    public Integer getNocuoi() {
        return this.nocuoi;
    }
    
    public void setNocuoi(Integer nocuoi) {
        this.nocuoi = nocuoi;
    }




}


