package com.app.bookstoreapp.entity;
// Generated Nov 8, 2018 10:55:04 AM by Hibernate Tools 4.3.1



/**
 * CustomersDiscountsId generated by hbm2java
 */
public class CustomersDiscountsId  implements java.io.Serializable {


     private Integer customerId;
     private Integer discountId;

    public CustomersDiscountsId() {
    }

    public CustomersDiscountsId(Integer customerId, Integer discountId) {
       this.customerId = customerId;
       this.discountId = discountId;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public Integer getDiscountId() {
        return this.discountId;
    }
    
    public void setDiscountId(Integer discountId) {
        this.discountId = discountId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CustomersDiscountsId) ) return false;
		 CustomersDiscountsId castOther = ( CustomersDiscountsId ) other; 
         
		 return ( (this.getCustomerId()==castOther.getCustomerId()) || ( this.getCustomerId()!=null && castOther.getCustomerId()!=null && this.getCustomerId().equals(castOther.getCustomerId()) ) )
 && ( (this.getDiscountId()==castOther.getDiscountId()) || ( this.getDiscountId()!=null && castOther.getDiscountId()!=null && this.getDiscountId().equals(castOther.getDiscountId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCustomerId() == null ? 0 : this.getCustomerId().hashCode() );
         result = 37 * result + ( getDiscountId() == null ? 0 : this.getDiscountId().hashCode() );
         return result;
   }   


}


