package com.app.bookstoreapp.entity;
// Generated Nov 8, 2018 10:55:04 AM by Hibernate Tools 4.3.1



/**
 * CustomersDiscounts generated by hbm2java
 */
public class CustomersDiscounts  implements java.io.Serializable {


     private CustomersDiscountsId id;
     private Customers customers;
     private Discounts discounts;

    public CustomersDiscounts() {
    }

	
    public CustomersDiscounts(CustomersDiscountsId id) {
        this.id = id;
    }
    public CustomersDiscounts(CustomersDiscountsId id, Customers customers, Discounts discounts) {
       this.id = id;
       this.customers = customers;
       this.discounts = discounts;
    }
   
    public CustomersDiscountsId getId() {
        return this.id;
    }
    
    public void setId(CustomersDiscountsId id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Discounts getDiscounts() {
        return this.discounts;
    }
    
    public void setDiscounts(Discounts discounts) {
        this.discounts = discounts;
    }




}


