package com.app.bookstoreapp.entity;
// Generated Nov 8, 2018 10:55:04 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Discounts generated by hbm2java
 */
public class Discounts  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Integer value;
     private Set customersDiscountses = new HashSet(0);
     private Set booksDiscountses = new HashSet(0);

    public Discounts() {
    }

    public Discounts(String name, Integer value, Set customersDiscountses, Set booksDiscountses) {
       this.name = name;
       this.value = value;
       this.customersDiscountses = customersDiscountses;
       this.booksDiscountses = booksDiscountses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getValue() {
        return this.value;
    }
    
    public void setValue(Integer value) {
        this.value = value;
    }
    public Set getCustomersDiscountses() {
        return this.customersDiscountses;
    }
    
    public void setCustomersDiscountses(Set customersDiscountses) {
        this.customersDiscountses = customersDiscountses;
    }
    public Set getBooksDiscountses() {
        return this.booksDiscountses;
    }
    
    public void setBooksDiscountses(Set booksDiscountses) {
        this.booksDiscountses = booksDiscountses;
    }




}


