package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1



/**
 * HoadonId generated by hbm2java
 */
public class HoadonId  implements java.io.Serializable {


     private int sohd;
     private int makh;
     private int manv;

    public HoadonId() {
    }

    public HoadonId(int sohd, int makh, int manv) {
       this.sohd = sohd;
       this.makh = makh;
       this.manv = manv;
    }
   
    public int getSohd() {
        return this.sohd;
    }
    
    public void setSohd(int sohd) {
        this.sohd = sohd;
    }
    public int getMakh() {
        return this.makh;
    }
    
    public void setMakh(int makh) {
        this.makh = makh;
    }
    public int getManv() {
        return this.manv;
    }
    
    public void setManv(int manv) {
        this.manv = manv;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HoadonId) ) return false;
		 HoadonId castOther = ( HoadonId ) other; 
         
		 return (this.getSohd()==castOther.getSohd())
 && (this.getMakh()==castOther.getMakh())
 && (this.getManv()==castOther.getManv());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSohd();
         result = 37 * result + this.getMakh();
         result = 37 * result + this.getManv();
         return result;
   }   


}


