package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hoadon generated by hbm2java
 */
public class Hoadon  implements java.io.Serializable {


     private HoadonId id;
     private Khachhang khachhang;
     private Nhanvien nhanvien;
     private Date ngaylap;
     private Integer tonggiatri;

    public Hoadon() {
    }

	
    public Hoadon(HoadonId id, Khachhang khachhang, Nhanvien nhanvien) {
        this.id = id;
        this.khachhang = khachhang;
        this.nhanvien = nhanvien;
    }
    public Hoadon(HoadonId id, Khachhang khachhang, Nhanvien nhanvien, Date ngaylap, Integer tonggiatri) {
       this.id = id;
       this.khachhang = khachhang;
       this.nhanvien = nhanvien;
       this.ngaylap = ngaylap;
       this.tonggiatri = tonggiatri;
    }
   
    public HoadonId getId() {
        return this.id;
    }
    
    public void setId(HoadonId id) {
        this.id = id;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Date getNgaylap() {
        return this.ngaylap;
    }
    
    public void setNgaylap(Date ngaylap) {
        this.ngaylap = ngaylap;
    }
    public Integer getTonggiatri() {
        return this.tonggiatri;
    }
    
    public void setTonggiatri(Integer tonggiatri) {
        this.tonggiatri = tonggiatri;
    }




}


