package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private int makh;
     private String tenkh;
     private String gioitinh;
     private String diachi;
     private String sdt;
     private Set hoadons = new HashSet(0);
     private Set ctCongnos = new HashSet(0);

    public Khachhang() {
    }

	
    public Khachhang(int makh) {
        this.makh = makh;
    }
    public Khachhang(int makh, String tenkh, String gioitinh, String diachi, String sdt, Set hoadons, Set ctCongnos) {
       this.makh = makh;
       this.tenkh = tenkh;
       this.gioitinh = gioitinh;
       this.diachi = diachi;
       this.sdt = sdt;
       this.hoadons = hoadons;
       this.ctCongnos = ctCongnos;
    }
   
    public int getMakh() {
        return this.makh;
    }
    
    public void setMakh(int makh) {
        this.makh = makh;
    }
    public String getTenkh() {
        return this.tenkh;
    }
    
    public void setTenkh(String tenkh) {
        this.tenkh = tenkh;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }
    public Set getCtCongnos() {
        return this.ctCongnos;
    }
    
    public void setCtCongnos(Set ctCongnos) {
        this.ctCongnos = ctCongnos;
    }




}


