package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private int manv;
     private String tennv;
     private String chucvu;
     private String gioitinh;
     private String diachi;
     private String sdt;
     private String username;
     private String password;
     private Set hoadons = new HashSet(0);
     private Set phieunhaps = new HashSet(0);

    public Nhanvien() {
    }

	
    public Nhanvien(int manv) {
        this.manv = manv;
    }
    public Nhanvien(int manv, String tennv, String chucvu, String gioitinh, String diachi, String sdt, Set hoadons, Set phieunhaps) {
       this.manv = manv;
       this.tennv = tennv;
       this.chucvu = chucvu;
       this.gioitinh = gioitinh;
       this.diachi = diachi;
       this.sdt = sdt;
       this.hoadons = hoadons;
       this.phieunhaps = phieunhaps;
    }
   
    public int getManv() {
        return this.manv;
    }
    
    public void setManv(int manv) {
        this.manv = manv;
    }
    public String getTennv() {
        return this.tennv;
    }
    
    public void setTennv(String tennv) {
        this.tennv = tennv;
    }
    public String getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(String chucvu) {
        this.chucvu = chucvu;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public Set getHoadons() {
        return this.hoadons;
    }
    
    public void setHoadons(Set hoadons) {
        this.hoadons = hoadons;
    }
    public Set getPhieunhaps() {
        return this.phieunhaps;
    }
    
    public void setPhieunhaps(Set phieunhaps) {
        this.phieunhaps = phieunhaps;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


}


