package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nhaxuatban generated by hbm2java
 */
public class Nhaxuatban  implements java.io.Serializable {


     private int manxb;
     private String tennxb;
     private String diachi;
     private String sdt;
     private String email;
     private Set saches = new HashSet(0);

    public Nhaxuatban() {
    }

	
    public Nhaxuatban(int manxb) {
        this.manxb = manxb;
    }
    public Nhaxuatban(int manxb, String tennxb, String diachi, String sdt, String email, Set saches) {
       this.manxb = manxb;
       this.tennxb = tennxb;
       this.diachi = diachi;
       this.sdt = sdt;
       this.email = email;
       this.saches = saches;
    }
   
    public int getManxb() {
        return this.manxb;
    }
    
    public void setManxb(int manxb) {
        this.manxb = manxb;
    }
    public String getTennxb() {
        return this.tennxb;
    }
    
    public void setTennxb(String tennxb) {
        this.tennxb = tennxb;
    }
    public String getDiachi() {
        return this.diachi;
    }
    
    public void setDiachi(String diachi) {
        this.diachi = diachi;
    }
    public String getSdt() {
        return this.sdt;
    }
    
    public void setSdt(String sdt) {
        this.sdt = sdt;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set saches) {
        this.saches = saches;
    }




}


