package com.app.bookstoreapp.entity;
// Generated Nov 8, 2018 10:55:04 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private Customers customers;
     private Employees employees;
     private Date orderDate;
     private Integer subtotal;
     private Integer discount;
     private Integer shipping;
     private Integer total;

    public Orders() {
    }

    public Orders(Customers customers, Employees employees, Date orderDate, Integer subtotal, Integer discount, Integer shipping, Integer total) {
       this.customers = customers;
       this.employees = employees;
       this.orderDate = orderDate;
       this.subtotal = subtotal;
       this.discount = discount;
       this.shipping = shipping;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public Employees getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Employees employees) {
        this.employees = employees;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public Integer getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(Integer subtotal) {
        this.subtotal = subtotal;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public Integer getShipping() {
        return this.shipping;
    }
    
    public void setShipping(Integer shipping) {
        this.shipping = shipping;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }




}


