package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Phieunhap generated by hbm2java
 */
public class Phieunhap  implements java.io.Serializable {


     private int sopn;
     private Nhanvien nhanvien;
     private Integer manxb;
     private Date ngaylap;
     private Integer tonggiatri;

    public Phieunhap() {
    }

	
    public Phieunhap(int sopn) {
        this.sopn = sopn;
    }
    public Phieunhap(int sopn, Nhanvien nhanvien, Integer manxb, Date ngaylap, Integer tonggiatri) {
       this.sopn = sopn;
       this.nhanvien = nhanvien;
       this.manxb = manxb;
       this.ngaylap = ngaylap;
       this.tonggiatri = tonggiatri;
    }
   
    public int getSopn() {
        return this.sopn;
    }
    
    public void setSopn(int sopn) {
        this.sopn = sopn;
    }
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }
    public Integer getManxb() {
        return this.manxb;
    }
    
    public void setManxb(Integer manxb) {
        this.manxb = manxb;
    }
    public Date getNgaylap() {
        return this.ngaylap;
    }
    
    public void setNgaylap(Date ngaylap) {
        this.ngaylap = ngaylap;
    }
    public Integer getTonggiatri() {
        return this.tonggiatri;
    }
    
    public void setTonggiatri(Integer tonggiatri) {
        this.tonggiatri = tonggiatri;
    }




}


