package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1



/**
 * SachId generated by hbm2java
 */
public class SachId  implements java.io.Serializable {


     private int masach;
     private int matheloai;
     private int manxb;

    public SachId() {
    }

    public SachId(int masach, int matheloai, int manxb) {
       this.masach = masach;
       this.matheloai = matheloai;
       this.manxb = manxb;
    }
   
    public int getMasach() {
        return this.masach;
    }
    
    public void setMasach(int masach) {
        this.masach = masach;
    }
    public int getMatheloai() {
        return this.matheloai;
    }
    
    public void setMatheloai(int matheloai) {
        this.matheloai = matheloai;
    }
    public int getManxb() {
        return this.manxb;
    }
    
    public void setManxb(int manxb) {
        this.manxb = manxb;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SachId) ) return false;
		 SachId castOther = ( SachId ) other; 
         
		 return (this.getMasach()==castOther.getMasach())
 && (this.getMatheloai()==castOther.getMatheloai())
 && (this.getManxb()==castOther.getManxb());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMasach();
         result = 37 * result + this.getMatheloai();
         result = 37 * result + this.getManxb();
         return result;
   }   


}


