package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1



/**
 * Sach generated by hbm2java
 */
public class Sach  implements java.io.Serializable {


     private SachId id;
     private Nhaxuatban nhaxuatban;
     private Theloai theloai;
     private Integer matagia;
     private Integer soluong;
     private Integer dongia;
     private String tensach;

    public Sach() {
    }

	
    public Sach(SachId id, Nhaxuatban nhaxuatban, Theloai theloai) {
        this.id = id;
        this.nhaxuatban = nhaxuatban;
        this.theloai = theloai;
    }
    public Sach(SachId id, Nhaxuatban nhaxuatban, Theloai theloai, Integer matagia, Integer soluong, Integer dongia, String tensach) {
       this.id = id;
       this.nhaxuatban = nhaxuatban;
       this.theloai = theloai;
       this.matagia = matagia;
       this.soluong = soluong;
       this.dongia = dongia;
       this.tensach = tensach;
    }
   
    public SachId getId() {
        return this.id;
    }
    
    public void setId(SachId id) {
        this.id = id;
    }
    public Nhaxuatban getNhaxuatban() {
        return this.nhaxuatban;
    }
    
    public void setNhaxuatban(Nhaxuatban nhaxuatban) {
        this.nhaxuatban = nhaxuatban;
    }
    public Theloai getTheloai() {
        return this.theloai;
    }
    
    public void setTheloai(Theloai theloai) {
        this.theloai = theloai;
    }
    public Integer getMatagia() {
        return this.matagia;
    }
    
    public void setMatagia(Integer matagia) {
        this.matagia = matagia;
    }
    public Integer getSoluong() {
        return this.soluong;
    }
    
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }
    public Integer getDongia() {
        return this.dongia;
    }
    
    public void setDongia(Integer dongia) {
        this.dongia = dongia;
    }
    public String getTensach() {
        return this.tensach;
    }
    
    public void setTensach(String tensach) {
        this.tensach = tensach;
    }




}


