package com.app.bookstoreapp.entity;
// Generated Oct 27, 2018 3:17:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Theloai generated by hbm2java
 */
public class Theloai  implements java.io.Serializable {


     private int matheloai;
     private String tentheloai;
     private Set saches = new HashSet(0);

    public Theloai() {
    }

	
    public Theloai(int matheloai) {
        this.matheloai = matheloai;
    }
    public Theloai(int matheloai, String tentheloai, Set saches) {
       this.matheloai = matheloai;
       this.tentheloai = tentheloai;
       this.saches = saches;
    }
   
    public int getMatheloai() {
        return this.matheloai;
    }
    
    public void setMatheloai(int matheloai) {
        this.matheloai = matheloai;
    }
    public String getTentheloai() {
        return this.tentheloai;
    }
    
    public void setTentheloai(String tentheloai) {
        this.tentheloai = tentheloai;
    }
    public Set getSaches() {
        return this.saches;
    }
    
    public void setSaches(Set saches) {
        this.saches = saches;
    }




}


